### ISSUE TITLE
Can I improve it and publish my own fork?

### ISSUE THREAD

**Issue by electricsteve** [kyle-hunady/villager-essentials#4]
I have made a fork of this project: [electricsteve/villager-essentials](https://github.com/electricsteve/villager-essentials) and made some changes (configs). I included a License in every file (except for the ones I didn't edit) that includes You as original author and me who modified it. Can I upload the modified version on [Modrinth](https://modrinth.com/) and update thigns on my own?

EDIT:
@kyle-hunady

**Comment by kyle-hunady** [comment]
oh yes! my apologies. please do. thanks
